### ISSUE TITLE
White overflow on right side

### ISSUE THREAD

**Issue by sk22** [Lean-Coders/website#7]
At least on mobile, there's a white overflow on the right side.
That's a bug in the website's CSS; probably some element is too big or has an unwanted margin.
A hacky solution could be to set the root element's x-overflow to hidden and width to 100vw or something.

![screenshot_20181206-234839](https://user-images.githubusercontent.com/6217438/49616620-b4a46380-f9b1-11e8-8de1-477a2a323688.png)

**Comment by livevie** [comment]
done
